import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "./GlobalProvider";
import AddToCart from "./components/AddToCart";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Product List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {children}
        {/* <GlobalProvider></GlobalProvider> */}
      </body>
    </html>
  );
}
